#! /bin/sh
#
# httpd          Start/Stop the apache web server.
#
### BEGIN INIT INFO
# Provides:          apache2.2
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

. /lib/lsb/init-functions
APACHECTL=/usr/bin/apachectl

# See how we were called.
case "$1" in
    start)
	    log_daemon_msg "Starting web server" "apache2.2"
		if $APACHECTL start; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    stop)
	    log_daemon_msg "Stopping web server" "apache2.2"
		if $APACHECTL graceful-stop; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    restart)
	    log_daemon_msg "Restarting web server" "apache2.2"
  		if $APACHECTL graceful; then
              log_end_msg 0
          else
              log_end_msg 1
          fi
        ;;
	*)
		log_success_msg "Usage: /etc/init.d/httpd {start|stop|restart}"
		exit 1
	;;
esac
