#!/bin/bash

# http://software.complete.org/offlineimap
# http://software.complete.org/offlineimap/downloads

export VERSION='5.99.4'

cd /usr/local/src
wget http://software.complete.org/offlineimap/static/download_area/$VERSION/offlineimap_$VERSION.tar.gz
tar zxf offlineimap_$VERSION.tar.gz
cd offlineimap
/usr/local/bin/python setup.py install
