#!/bin/bash

# Update the timestamp.
perl -E 'say scalar time' > /var/www/master.pgxn.org/meta/timestamp
echo '# Do not delete this file' >> /var/www/master.pgxn.org/meta/timestamp

# Check all mirrors.
/var/www/manager.pgxn.org/bin/check_mirrors /var/www/master.pgxn.org/meta/mirrors.json
